spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/assetAllocation #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  sql:
#    init:
#      mode: always


  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
#    defer-datasource-initialization: true

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.orm.jdbc.bind: trace #띄어쓰기 2칸

jwt:
  header: Authorization
  secret: aG9uZ2lrX3VuaXZlcnNpdHlfY29tcHV0ZXJFbmdpbmVlcmluZ19ncmFkdWF0aW9uX3Byb2plY3Rfc2VjcmV0S2V5X2ltX2p1bmh5dWs=
  token-validity-in-seconds: 86400